FROM alpine:latest

WORKDIR /app

COPY requirements.txt /app
COPY devops /app/devops  # Ensure the correct path

# Install required packages
RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    python3 -m venv venv && \
    source venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

WORKDIR /app/devops





