FROM alpine:latest

WORKDIR /app

COPY requirements.txt /app
COPY devops /app

# Install required packages
RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

WORKDIR /app/devops





